[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.filesystem = spiffs

lib_deps =
  links2004/WebSockets @ ^2.4.2
  bblanchon/ArduinoJson @ ^6.21.2
  ArduinoOTA

build_flags =
  -DCONFIG_ASYNC_TCP_EVENT_QUEUE_SIZE=128
  -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
  -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
  -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"

[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
; upload_port = 192.168.0.50

